#import "template.typ": *
#let meta = conf.with(
  class: "",
  serialnumber: "",
  udc: "",
  confidence: "",
  cauthor: "张三",
  eauthor: "San Zhang",
  studentid: "12010000",
  ctitle: "南方科技大学学位论文模板",
  csubtitle: "一个Typst模版",
  etitle: "SUSTech thesis document template",
  esubtitle: "A Typst Template",
  department: "计算机科学与工程系",
  cmajor: "计算机科学与技术",
  emajor: "Some Major",
  csupervisor: "李四 教授",
  esupervisor: "Prof. Si Li",
  date: "二零二四年六月X日",
  cabstract: "本文介绍了 sustech-ug-thesis-typst 文档模板所提供的功能。",
  ckeywords: ("Typst", "模板"),
  eabstract: "This document introduces the features of the sustech-ug-thesis-typst template.",
  ekeywords: ("Typst", "Template"),
  acknowledgements: [感谢 Typst 开发者的辛勤付出。],
  linespacing: 1.5em,
  outlinedepth: 3,
  blind: false,
  listofimage: true,
  listoftable: true,
  listofcode: true,
  alwaysstartodd: true,
)
